[versions]
kotlin = "2.0.21"

plasmovoice = "2.1.6"
lombok = "1.18.30"
fabric-loader = "0.17.3"
architectury-loom = "1.9-SNAPSHOT"
buildconfig = "5.7.0"
neoforge = "21.1.192"

[libraries]
plasmovoice = { module = "su.plo.voice.api:client", version.ref = "plasmovoice" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
fabricloader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
neoforge = { module = "net.neoforged:neoforge", version.ref = "neoforge" }

[plugins]
loom = { id = "dev.architectury.loom", version.ref = "architectury-loom" }
buildconfig = { id = "com.github.gmazzo.buildconfig", version.ref = "buildconfig" }
